### ISSUE TITLE
Discuss the best way to make it a pre-commit plugin

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/typecov#3]
This check currently runs after `mypy` has been executed and a report is generated. But pre-commit hooks execute of all the files that has some change (commit wise).

To make it a pre-commit hook, I can think of two options.

1. Create a separate `check-typecov` which will act as the binding between `mypy` and `typecov`. For each file with changes, it will first execute `mypy` on that file and then execute `typecov` serially.
2. Make it a pre-commit plugin. i.e. it will execute `mypy` before evaluating the coverage for each file.

With both options, we may need to parse the `mypy.ini`/`.mypy.ini` file and give user the option to mention a custom mypy config file, from where we will get the coverage directory location.

**Comment by sayanarijit** [comment]
@zupo what do you suggest?

**Comment by zupo** [comment]
We do the test coverage check after tests finish, why would we want to run types coverage check as a pre-commit and not after mypy finishes?

**Comment by sayanarijit** [comment]
Right... I think that's the better option rather than using it as a pre-commit check.
Closing this issue.
