### ISSUE TITLE
How to read typecov report?

### ISSUE THREAD

**Issue by caseydm** [sayanarijit/typecov#5]
Can somebody tell me what the columns stand for in a type coverage report? Here is an example:

90112  128958   3643   5137 total
   3491    3491    249    249 myapp.cards.models
   3147    3147      0      0 myapp.tests.test_views
   1699    1699    104    104 myapp.invoices.models

From what I understand the far left column is functions type checked and the middle columns is the total functions in the module. When you divide those you get type coverage. But what are the other two columns?

**Comment by sayanarijit** [comment]
As per https://github.com/python/mypy/blob/master/mypy/report.py#L172, it's

```
imputed_annotated_lines   physical_lines   annotated_funcs   total_funcs
```
